{% set name = "google-cloud-dataproc-metastore" %}
{% set version = "1.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/google-cloud-dataproc-metastore-{{ version }}.tar.gz
  sha256: d596a5a7706ff9fae26b2de6d1ecb611a924cabd926148fc20c87d0bd631246e

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - google-api-core-grpc >=1.28.0,<3.0.0dev
    - proto-plus >=1.4.0

test:
  imports:
    - google.cloud.metastore_v1
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/googleapis/python-dataproc-metastore
  summary: Dataproc Metastore API client library
  license: Apache-2.0
  license_file: LICENSE
  dev_url: https://github.com/googleapis/python-dataproc-metastore
  doc_url: https://cloud.google.com/dataproc-metastore/docs

extra:
  recipe-maintainers:
    - xylar
